apiVersion: v1
kind: Secret
metadata:
  name: evm-postgres-secret
  namespace: evm-platform
  labels:
    app.kubernetes.io/part-of: enterprise-vision-mlops
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: local-dev-change-me
  POSTGRES_DB: mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: evm-minio-secret
  namespace: evm-platform
  labels:
    app.kubernetes.io/part-of: enterprise-vision-mlops
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: local-dev-change-me
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: local-dev-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: evm-grafana-secret
  namespace: evm-platform
  labels:
    app.kubernetes.io/part-of: enterprise-vision-mlops
type: Opaque
stringData:
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: local-dev-change-me
